version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: online_exam_db
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-online_exam}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'online_exam_mysql_data:/var/lib/mysql'
    networks:
      - online_exam_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    container_name: online_exam_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - online_exam_redis_data:/data
    networks:
      - online_exam_network

  mailpit:
    image: axllent/mailpit
    container_name: online_exam_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - online_exam_network

volumes:
  online_exam_mysql_data:
  online_exam_redis_data:


networks:
  online_exam_network:
    driver: bridge
